### ISSUE TITLE
Does it support connecting to emulator?

### ISSUE THREAD

**Issue by kanekv** [cloudspannerecosystem/pgadapter#7]

**Comment by j-clap** [comment]
Hi kanaekv, it should support any connection that expects Postgres wire protocol. Which emulator do you have in mind? I can fully confirm or deny with that information :)

Note that if it uses Postgres internal tables, some RegExes might need to be added in the command metadata file, but that should be easy :)

**Comment by kanekv** [comment]
@j-clap this one: https://cloud.google.com/spanner/docs/emulator

**Comment by j-clap** [comment]
As long as you provide the right connection string, it should connect to any Spanner supported back-end. That being said, this specific endpoint has not been tested, but theoretically it should work.

**Comment by kanekv** [comment]
Got it. Thanks!
